name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  salloc:
    name: Salloc
    uses: ./.github/workflows/salloc.yaml

  norminette:
    needs: salloc
    name: Norminette
    uses: ./.github/workflows/norminette.yaml

  build_ubuntu_22_04:
    needs: norminette
    name: Build on Ubuntu 22.04
    uses: ./.github/workflows/build.yaml
    with:
      ubuntu-version: 22.04

  build_ubuntu_latest:
    needs: norminette
    name: Build on Ubuntu latest
    uses: ./.github/workflows/build.yaml
